version: "3.9"

services:
  tests:
    build: .
    # note Docker doesn't exec the command using a shell so let's use one explictly 
    command: /bin/sh -c "cargo test -- -Z unstable-options --format json | tee results.txt"
    volumes:
      # bind mount a directory to share the output of the test runner
      - type: bind
        source: .
        target: /code
